### ISSUE TITLE
IDA7.5SP3无法加载插件

### ISSUE THREAD

**Issue by ArcEcho** [notify-bibi/ScyllaHide-IDA7.5#2]
![image](https://user-images.githubusercontent.com/7297514/161224533-d6fdc40e-d925-4d93-8759-6c617fc62c2d.png)

提示IDA\plugins\HookLibraryx64.dll: not IDA DLL file。
https://bbs.pediy.com/thread-264323.htm

**Comment by notify-bibi** [comment]
这个warning无关紧要哈, dll会被ida尝试加载, 但是这个dll不是给ida的, 是给本插件用来加载给目标进程的, 可以看看ida插件中有没有本插件, 或者按下快捷键看看有没有弹出来(ALT+X)
